import Dexie, { type Table } from "dexie";
import type {
  Annotation,
  Book,
  CaseScenario,
  CardState,
  Chapter,
  Flashcard,
  MediaFile,
  Question,
  QuestionState,
  QuizSession
} from "./types";

export interface Tombstone {
  /** `${table}:${id}` */
  key: string;
  table: SyncTable;
  id: string;
  updatedAt: number;
}

export interface MetaRow {
  key: string;
  value: unknown;
}

/** Tables whose rows are exchanged with other devices. */
export const SYNC_TABLES = [
  "annotations",
  "questionStates",
  "cardStates",
  "sessions",
  "userFlashcards",
  "userCases"
] as const;
export type SyncTable = (typeof SYNC_TABLES)[number];

export class NeuroQuizDB extends Dexie {
  books!: Table<Book, string>;
  chapters!: Table<Chapter, string>;
  questions!: Table<Question, string>;
  flashcards!: Table<Flashcard, string>;
  cases!: Table<CaseScenario, string>;
  media!: Table<MediaFile, string>;

  annotations!: Table<Annotation, string>;
  questionStates!: Table<QuestionState, string>;
  cardStates!: Table<CardState, string>;
  sessions!: Table<QuizSession, string>;
  /** Flashcards generated by AI or written by the user (synced). */
  userFlashcards!: Table<Flashcard, string>;
  /** Cases generated by AI or written by the user (synced). */
  userCases!: Table<CaseScenario, string>;

  tombstones!: Table<Tombstone, string>;
  meta!: Table<MetaRow, string>;

  constructor(name = "neuroquiz") {
    super(name);
    this.version(1).stores({
      books: "id, title",
      chapters: "id, bookId, order",
      questions: "id, bookId, chapterId, order",
      flashcards: "id, bookId, chapterId, questionId",
      cases: "id, bookId, chapterId",
      media: "id, bookId, name",
      annotations: "id, kind, topic, subtopic, *tags, updatedAt",
      questionStates: "questionId, srs.due, updatedAt",
      cardStates: "cardId, srs.due, updatedAt",
      sessions: "id, mode, startedAt, finishedAt, updatedAt",
      userFlashcards: "id, bookId, questionId, updatedAt",
      userCases: "id, bookId, updatedAt",
      tombstones: "key, table, updatedAt",
      meta: "key"
    });
  }
}

export const db = new NeuroQuizDB();

/** Primary-key field name of each synced table. */
export const SYNC_KEY: Record<SyncTable, string> = {
  annotations: "id",
  questionStates: "questionId",
  cardStates: "cardId",
  sessions: "id",
  userFlashcards: "id",
  userCases: "id"
};

export async function allFlashcards(): Promise<Flashcard[]> {
  const [a, b] = await Promise.all([db.flashcards.toArray(), db.userFlashcards.toArray()]);
  return [...a, ...b];
}

export async function allCases(): Promise<CaseScenario[]> {
  const [a, b] = await Promise.all([db.cases.toArray(), db.userCases.toArray()]);
  return [...a, ...b];
}

export async function getMeta<T>(key: string, fallback: T): Promise<T> {
  const row = await db.meta.get(key);
  return row ? (row.value as T) : fallback;
}

export async function setMeta(key: string, value: unknown): Promise<void> {
  await db.meta.put({ key, value });
}

/** Delete a synced row and leave a tombstone so other devices delete it too. */
export async function deleteSynced(table: SyncTable, id: string): Promise<void> {
  await db.transaction("rw", db.table(table), db.tombstones, async () => {
    await db.table(table).delete(id);
    await db.tombstones.put({ key: `${table}:${id}`, table, id, updatedAt: Date.now() });
  });
}

/**
 * question id → chapter id, read from the index only (no question bodies),
 * so screens that just count questions stay fast with large libraries.
 */
export async function questionChapterIndex(): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  await db.questions.orderBy("chapterId").eachKey((key, cursor) => {
    out.set(String(cursor.primaryKey), String(key));
  });
  return out;
}
